# Generated by Django 3.0.3 on 2020-09-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20200907_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.AlterField(
            model_name='profile',
            name='leaves_avai',
            field=models.CharField(max_length=2),
        ),
    ]
