# Generated by Django 3.0.3 on 2020-09-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20200907_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('approval', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=120, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
