# Generated by Django 3.0.3 on 2020-09-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20200907_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
