# Generated by Django 3.0.3 on 2020-09-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leaves_avai',
            field=models.CharField(default='10', max_length=2),
        ),
    ]
