# Generated by Django 3.0.3 on 2020-09-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_auto_20200908_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='mob_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
